# California Housing: Data Exploration

Goal: understand the features, target variable, data quality, distributions, relationships, and possible problems before building regression models.

Questions:
- What does each feature represent?
- Which features are related to house value?
- Are there missing values or outliers?
- Which features may require scaling or transformation?
- Does a linear relationship seem reasonable?

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.datasets import fetch_california_housing

sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)

In [3]:
housing = fetch_california_housing(as_frame=True)

df = housing.frame.copy()
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [7]:
df.shape

(20640, 9)

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
MedInc,20640.0,3.870671,1.899822,0.499900,2.563400,3.534800,4.743250,15.000100
HouseAge,20640.0,28.639486,12.585558,1.000000,18.000000,29.000000,37.000000,52.000000
AveRooms,20640.0,5.429000,2.474173,0.846154,4.440716,5.229129,6.052381,141.909091
AveBedrms,20640.0,1.096675,0.473911,0.333333,1.006079,1.048780,1.099526,34.066667
Population,20640.0,1425.476744,1132.462122,3.000000,787.000000,1166.000000,1725.000000,35682.000000
AveOccup,20640.0,3.070655,10.386050,0.692308,2.429741,2.818116,3.282261,1243.333333
Latitude,20640.0,35.631861,2.135952,32.540000,33.930000,34.260000,37.710000,41.950000
Longitude,20640.0,-119.569704,2.003532,-124.350000,-121.800000,-118.490000,-118.010000,-114.310000
MedHouseVal,20640.0,2.068558,1.153956,0.149990,1.196000,1.797000,2.647250,5.000010

Datasetcontains :
<li>20k+ records of houses.</li>
<li>6 useful input columns/features( total 8 )</li>
<li>Target range is (500k$ - 200k$) = 300k$</li>
<li>features with very different scale: Population</li>
<li>features with Suspicious minimum or maximum values: AveRooms,AveBedrms,AveOccup</li>

In [14]:
df.isna().sum() # no missing values

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [18]:
df.duplicated().sum() # no duplicate rows

np.int64(0)

In [20]:
df.nunique().sort_values()

HouseAge          52
Longitude        844
Latitude         862
MedHouseVal     3842
Population      3888
MedInc         12928
AveBedrms      14233
AveOccup       18841
AveRooms       19392
dtype: int64